### ISSUE TITLE
Reload sent messages and commands

### ISSUE THREAD

**Issue by fueledbycoffee** [shadowRR/kozette#6]
It would be great to be able to reload sent messages or commands by pressing the up key in the chat input like the linux terminal.

**Comment by shadowRR** [comment]
Hum, not sure to see the point ? It's not like you're gonna reuse the same message again and again...
Except when spamming...

**Comment by fueledbycoffee** [comment]
/nick 𝕾𝖎𝖔𝖓 isn't easy to type so when i switch to /nick 𝕾𝖎𝖔𝖓[Miam] etc. i have to c/C my previous nick to rechange. If we could reload previous messages or commands all i have to do is upkey and remove the extra

**Comment by shadowRR** [comment]
well i'm gonna add some sort of a status /status instead. It would make more sense to me, than actually having to change you're nick every time...
