### ISSUE TITLE
Parse links

### ISSUE THREAD

**Issue by fueledbycoffee** [shadowRR/kozette#8]
It would be great to make links clickable and or parse them to show a preview of the link.

You could go a step further and load youtube videos directly in the feed :)

**Comment by shadowRR** [comment]
Yep. Was just looking at ways to do this. I think i'm gonna implement it in two different ways.

The first one will be a classic link in a message, which will just be that. The other will be through the /link command who will go get the oEmbed (if available) to show a preview.
